name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: say-hello
        run: echo "hello"
      - name: say-ready
        run: |
          echo "are you ready?" 
          echo "maybe you are ready" 
      - name: say-bye
        run: echo "goodbye!"
